# Generated by Django 6.1 on 2026-10-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('PROJECT_MANAGER', 'Project Manager'), ('COT_HOD', 'COT / HOD'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('QA', 'QA')], default='EMPLOYEE', max_length=20),
        ),
    ]
